### ISSUE TITLE
Kunde-feedback: Menu virker ikke i IE & Firefox

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#1]
En kunde skrev, at han ikke kunne se menuen i Internet explorer og Firefox. Jeg fik dette billede af ham:
![image](https://cloud.githubusercontent.com/assets/13694222/12826115/c83fd0dc-cb79-11e5-8201-c5f745e31333.png)

**Comment by Mahnkopf** [comment]
Det er rigtig. Den menu animation vi brugte, virker ikke på Internet Explorer og Firefox. 
Prøv evt. på forskellige browsere - http://codepen.io/iremlopsum/pen/QwJqvR
Derfor er menu animationen ændret til en jeg selv har lavet og den passer til alle browsere.

**Comment by rfenklt** [comment]
Jeg hører lige personen der fandt fejlen, om han kan se at den er rettet. Hvis den er lukker jeg den her :)

**Comment by Mahnkopf** [comment]
fixed
