### ISSUE TITLE
Casebilleder skaleres forkert

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#10]
Nogle af billederne på cases skalerer forkert:
<img width="842" alt="screen shot 2016-02-04 at 8 50 29 pm" src="https://cloud.githubusercontent.com/assets/13694222/12827658/0118ee6e-cb81-11e5-81ec-28bc1ab99725.png">

**Comment by Mahnkopf** [comment]
Dette var en fejl og jeg opdagede et par af dem. De var bare ikke så slemme. De er nu rettet

**Comment by Mahnkopf** [comment]
Dette gør dog at teksten i venstre sides område bliver meget større. Det skal vi lige finde ud af. Som sagt er billederne i fuld brede og højden kan vi så ikke gøre meget ved. Det er endnu et diskussions emne :)

**Comment by rfenklt** [comment]
Husk mig lige på at vi skal have snakket om dette :)

**Comment by Mahnkopf** [comment]
fixed
