### ISSUE TITLE
Afstande fra overskrift

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#11]
Alle overskrifter skal have samme afstand fra top til tekst på alle cases.

<img width="749" alt="screen shot 2016-02-04 at 8 53 33 pm" src="https://cloud.githubusercontent.com/assets/13694222/12827758/77c5075a-cb81-11e5-9f84-308796df90d1.png">
<img width="676" alt="screen shot 2016-02-04 at 8 53 41 pm" src="https://cloud.githubusercontent.com/assets/13694222/12827759/77c6110e-cb81-11e5-89f3-90f54bf6281b.png">

**Comment by Mahnkopf** [comment]
Det er nu rettet
