### ISSUE TITLE
Nyheds-opsætning

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#12]
Kan man lave custom-tekstopsætning i Wordpress, så jeg selv kan bestemme hvornår teksten skal skille i kolonner?

**Comment by Mahnkopf** [comment]
Her har jeg gjort at den kigger på om højden på teksten er højere end siden. Hvis ja, bliver den delt i 2 kolonner og det gør den lidt random. Men her kan vi også bare lave vores eget layout for hver case/nyhed.

**Comment by rfenklt** [comment]
Det afgør du hvad der er nemmest. Bare teksten står pænt :)

**Comment by Mahnkopf** [comment]
fixed
