### ISSUE TITLE
Margin på jobopslag

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#17]
Der er noget margin på Job hos enklt der skal ændres til det der vises på Praktik hos enklt
![img_0253](https://cloud.githubusercontent.com/assets/13694222/12872287/9edf9114-cd9f-11e5-958d-b99d55260159.jpg)
![img_0254](https://cloud.githubusercontent.com/assets/13694222/12872288/9edfc206-cd9f-11e5-8011-33a50755d390.jpg)

**Comment by Mahnkopf** [comment]
fixed
