### ISSUE TITLE
Etkigbagved - åben nyhed

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#18]
Billedet ser ikke ud til at blive vist på mobil?
Derudover er teksten to kolonner, hvor den på mobil kun skal være en kolonne :)

De mellemrum der er mellem tilbageknappen, menuknappen og logoet, tænker jeg at det blot er fordi der ikke er noget baggrundsbillede?

![img_0255](https://cloud.githubusercontent.com/assets/13694222/12872298/f58dcbe8-cd9f-11e5-850b-27b85083d164.jpg)

**Comment by Mahnkopf** [comment]
fixed
