### ISSUE TITLE
Kontakt - Padding/kort/adresse

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#19]
På kontaktsiden skal der lidt mindre linjeafstand mellem hello@enklt.dk og telefonnummeret.
Kortet ser ud til at være zoomet ud? Skal der laves et billede til mobil, så man kan se hvad gaderne hedder? :smile: 
Kan adressen få noget mere padding hele vejen rundt? Det er meget sammenpresset i containeren? Derudover må postnummeret gerne komme ned i ny linje. Linjeafstanden må også gerne reduceres.

![img_0256](https://cloud.githubusercontent.com/assets/13694222/12872307/50693930-cda0-11e5-9cf1-8f04c034edbf.jpg)

**Comment by Mahnkopf** [comment]
fixed
