### ISSUE TITLE
Kunde-feedback: Ingen adgang til websitet

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#2]
En kunde skrev at han overhovedet ikke kunne komme ind på vores site, på flere enheder. Han er selv udvikler, og kunne give et konkret eksempel på problemet:
<img width="407" alt="screen shot 2016-02-04 at 8 02 53 pm" src="https://cloud.githubusercontent.com/assets/13694222/12826373/17940c60-cb7b-11e5-98c4-1c37b8848a40.png">
<img width="401" alt="screen shot 2016-02-04 at 8 03 10 pm" src="https://cloud.githubusercontent.com/assets/13694222/12826371/17920028-cb7b-11e5-8e38-11080853eac5.png">
<img width="403" alt="screen shot 2016-02-04 at 8 03 24 pm" src="https://cloud.githubusercontent.com/assets/13694222/12826372/1793ca3e-cb7b-11e5-809f-3af9c84c56dc.png">
<img width="399" alt="screen shot 2016-02-04 at 8 03 31 pm" src="https://cloud.githubusercontent.com/assets/13694222/12826370/178fe75c-cb7b-11e5-92a7-0f26d53913c0.png">
![12632968_10153375713022514_1962994191_o](https://cloud.githubusercontent.com/assets/13694222/12826389/20e68176-cb7b-11e5-8034-05237ea6bc1f.jpg)
<img width="403" alt="screen shot 2016-02-04 at 8 03 51 pm" src="https://cloud.githubusercontent.com/assets/13694222/12826398/2883661a-cb7b-11e5-8f00-7f93e77f20ac.png">
<img width="391" alt="screen shot 2016-02-04 at 8 03 57 pm" src="https://cloud.githubusercontent.com/assets/13694222/12826400/28871c06-cb7b-11e5-8316-8a3fda4e6c50.png">
<img width="395" alt="screen shot 2016-02-04 at 8 04 03 pm" src="https://cloud.githubusercontent.com/assets/13694222/12826397/28829208-cb7b-11e5-95cb-7c35f624c0ba.png">
<img width="396" alt="screen shot 2016-02-04 at 8 04 09 pm" src="https://cloud.githubusercontent.com/assets/13694222/12826399/2884c7bc-cb7b-11e5-8845-72f50846b5cf.png">

**Comment by Mahnkopf** [comment]
Dette er en af de mere svære issues. Som jeg kan se udfra hans billede er det den kode han mener der giver fejl, der giver fejlen. Den bruger vi dog til kortet i kontakt knappen, når man er på mobil og den giver ikke fejl for mig. Men den er fjernet indtil vi finder en løsning. Så nu burde han i det mindste kunne få adgang og se noget. Ellers er der noget andet galt. Jeg kan ikke selv se flere store fejl der forhindre ham i det. 

Da jeg startede i dag med at kode installerede jeg alle de kendte browsere og oplevede ikke en side der var hvid eller ikke kunne vises. Så jeg er uforstående over han fra start ikke har kunne se noget.

**Comment by rfenklt** [comment]
Jeg har skrevet til personen, og hørt om fejlen er udbedret.

**Comment by rfenklt** [comment]
Han har meldt tilbage at der nu ingen problemer er! Jeg lukker den her, når du har godkendt :smiley:

**Comment by Mahnkopf** [comment]
Det er godtkendt og du kan bare slette den her sag. Jeg har styr på det fjernede kode og skal nok implementere det vi mangler igen
