### ISSUE TITLE
Åbne cases - faktabokse

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#23]
Der må gerne komme noget ekstra venstre-margin på, mens teksten bliver en anelse mindre?
Derudover er der noget padding som skal gerne være ens i både top og bund. 
Derudover er der også et lille mellemrum mellem faktaboks og det næste billede.

![img_0260](https://cloud.githubusercontent.com/assets/13694222/12872342/0870f1f8-cda1-11e5-9bf5-3027f3416006.jpg)

**Comment by Mahnkopf** [comment]
fixed
