### ISSUE TITLE
Kompetencer på forsiden

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#26]
En bruger har gjort mig opmærksom på dette skærmbillede. Han kan ikke se alle kompetencerne på siden, hvilket må betyde at hans skærm er i et mærkeligt format? Hvordan får vi rettet dette?

![12675144_10208259340030173_1380484388_o](https://cloud.githubusercontent.com/assets/13694222/12875325/e0950830-cde7-11e5-9136-8be1de22b68c.jpg)

**Comment by Mahnkopf** [comment]
Han har godt nok en lille skærm. Men det er fixet og jeg har set nogle flere issues i den bold gade
