### ISSUE TITLE
Jobopslag

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#27]
Vi er som sagt igang med få ansat nogle kørende sælgere, som skal sælge produkter for enklt. I den forbindelse skal vi have kontakter til udviklere og designere der kan bistå os, hvis vi på et tidspunkt for for meget at lave. Derfor skal vi have siden for åbne jobopslag udviklet. Teksterne er udarbejdet, så vi mangler blot at få udarbejdet billederne dertil.

Eksempel på jobopslag (Se bort fra lokationen på kortet):

![hvemervi_job_opened](https://cloud.githubusercontent.com/assets/13694222/12883672/a3093546-ce59-11e5-81d3-750da15483f2.jpg)

**Comment by Mahnkopf** [comment]
fixed
