### ISSUE TITLE
Crawl-errors

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#28]
Vi har 8 sider der får en 404-sider ifht. en analyse af Google:

<img width="1077" alt="screen shot 2016-02-08 at 2 48 41 pm" src="https://cloud.githubusercontent.com/assets/13694222/12887225/34645430-ce73-11e5-90ad-13d4ec0fbd7f.png">

**Comment by Mahnkopf** [comment]
Ved ikke hvad dette drejer sig om. Jeg har ikke undersøgt Crawl eller google analytics nærmere. Men jeg kan se at vi ikke bruger de links google giver fejl. Det må vi lige snakke om

**Comment by rfenklt** [comment]
Er det ikke blot 404-sider der ikke eksisterer længere? Eller links der linker til de forkerte sider? De skal vel bare fjernes eller tilrettes :)?

**Comment by Mahnkopf** [comment]
Dette er ikke gældende mere, da det er en ny version. Du må analysere igen
