### ISSUE TITLE
Billeder skalerer mærkeligt

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#3]
Vi skal have fundet en løsning på skaleringen af medarbejderbilleder og nyhedsbilleder, da de på større skærmstørrelser bliver aflange og så er det kun toppen af billederne der ses. Eksempel:
<img width="1680" alt="screen shot 2016-02-04 at 8 15 29 pm" src="https://cloud.githubusercontent.com/assets/13694222/12826599/119583a6-cb7c-11e5-825f-87fa92f599b0.png">

**Comment by Mahnkopf** [comment]
Dette problem lagde jeg mærke til, da jeg fandt løsningen på at vise de rigtige størrelser billeder. Som du kan se er billedet 100% bredt og dit design siger at den skal have en vis højde. Det vil så sige at billedet vokser i højden, men containeren gør ikke (Som designet dikterer). Løsningen jeg ser her: Er at gøre containeren højere, på de store skærme. Som du kan se på billedet, passer det fint til størrelser under 1500px.
![screen shot 2016-02-06 at 7 42 32 am](https://cloud.githubusercontent.com/assets/7810308/12865163/78de3d6c-cca5-11e5-8390-81bf020f010c.png)

**Comment by rfenklt** [comment]
Kan man gøre containeren med billedet vokser i både højde og bredde, når man ændrer skærmstørrelse? Og vil det afhjælpe billederne på nyheds-siden også?

**Comment by Mahnkopf** [comment]
fixed
