### ISSUE TITLE
Stavefejl - etkigbagved

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#30]
Stavefejl i overskriften og URL - Ændres til 'Godt nytår 2016' og enklt.dk/etkigbagved/godt-nytaar-2016/:

<img width="275" alt="screen shot 2016-02-09 at 11 30 38 am" src="https://cloud.githubusercontent.com/assets/13694222/12913709/a2382a6a-cf20-11e5-9603-cc4ddadc079a.png">
<img width="466" alt="screen shot 2016-02-09 at 11 30 43 am" src="https://cloud.githubusercontent.com/assets/13694222/12913708/a22d653a-cf20-11e5-81be-4b3d6710e102.png">

**Comment by Mahnkopf** [comment]
fixed
