### ISSUE TITLE
Medarbejderinformationer skal samstemmes

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#4]
Medarbejderinformationerne står forskelligt på forsiden og kontakt-siden. Den styling er på kontaktsiden.

<img width="843" alt="screen shot 2016-02-04 at 8 18 06 pm" src="https://cloud.githubusercontent.com/assets/13694222/12826710/b862bbea-cb7c-11e5-9c46-d0ba128f5a2c.png">
<img width="854" alt="screen shot 2016-02-04 at 8 18 21 pm" src="https://cloud.githubusercontent.com/assets/13694222/12826711/b8637d5a-cb7c-11e5-9e65-346d09d6502a.png">

**Comment by Mahnkopf** [comment]
Det er nu rettet

**Comment by rfenklt** [comment]
Der er noget padding der skal tilrettes på den der findes på forsiden. De ser ikke ud til at være samme størrelse. Teksten står fint:
<img width="834" alt="screen shot 2016-02-07 at 12 53 29 pm" src="https://cloud.githubusercontent.com/assets/13694222/12872138/dda62b3e-cd99-11e5-97a0-98e5ccac54e8.png">
<img width="833" alt="screen shot 2016-02-07 at 12 53 35 pm" src="https://cloud.githubusercontent.com/assets/13694222/12872139/dda7b1de-cd99-11e5-92fa-e4f04a8e67b1.png">

**Comment by Mahnkopf** [comment]
fixed
