### ISSUE TITLE
Cases loader langsomt på forsiden

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#6]
Når cachen bliver ryddet, og siden refreshes, loader billederne af cases på forsiden langsomt (specielt Forza Magazine-billedet). Skal billederne fylde mindre før det afhjælpes?

**Comment by Mahnkopf** [comment]
Denne opgave har jeg taget som den sidste. Det, der er vores problem her er det wordpress plugin(WP TILES). Jeg har installeret nogle optimizing plugins som skulle hjælpe. Jeg må dog vente for at se forbedringen. Ellers må jeg lave mit eget grid layout. Det vil jeg bare gerne undgå i første omgang :)

**Comment by rfenklt** [comment]
Ingen grund til at bruge til på at lave dit eget grid. Ville det hjælpe hvis vi købte det tiles-plugin du sendte mig i tidernes morgen?

**Comment by Mahnkopf** [comment]
fixed
