### ISSUE TITLE
Faktabokse på cases

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#7]
Alle faktabokse skal have ens afstande på alle cases - både i højden og i bredden. Derudover skal vi have en line-height på 35px .

<img width="816" alt="screen shot 2016-02-04 at 8 30 38 pm" src="https://cloud.githubusercontent.com/assets/13694222/12827285/3c42cfc0-cb7f-11e5-9e6b-be0ffe95190b.png">

**Comment by Mahnkopf** [comment]
Det er nu rettet

**Comment by rfenklt** [comment]
Venstremargin ser ud til at passe. Men der er stadig problemer med  afstand fra teksten til bund. Kan man lave det sådan, at det er teksten der definerer størrelsen på kassen? Så der altid er X-antal pixels i top såvel som bund?
<img width="809" alt="screen shot 2016-02-07 at 12 56 30 pm" src="https://cloud.githubusercontent.com/assets/13694222/12872150/69805d5a-cd9a-11e5-92a8-6ef40057fe43.png">
<img width="808" alt="screen shot 2016-02-07 at 12 56 40 pm" src="https://cloud.githubusercontent.com/assets/13694222/12872148/697f039c-cd9a-11e5-90fb-26f2ab775004.png">
<img width="809" alt="screen shot 2016-02-07 at 12 57 00 pm" src="https://cloud.githubusercontent.com/assets/13694222/12872149/697f9604-cd9a-11e5-932d-1365b805fb24.png">

**Comment by Mahnkopf** [comment]
fixed
