### ISSUE TITLE
Afstand fra case-beskrivelse til container

### ISSUE THREAD

**Issue by rfenklt** [enklt/web#8]
Der skal være mindre afstand fra case-beskrivelse til container. 

Fra:
<img width="850" alt="screen shot 2016-02-04 at 8 39 07 pm" src="https://cloud.githubusercontent.com/assets/13694222/12827419/f7d57f1c-cb7f-11e5-8db6-a104fd0dcacf.png">

Til:
<img width="732" alt="screen shot 2016-02-04 at 8 43 15 pm" src="https://cloud.githubusercontent.com/assets/13694222/12827423/fbee3850-cb7f-11e5-8019-ffda621a2f3c.png">

**Comment by Mahnkopf** [comment]
Denne afstand er afgørende af billederne i højre side og jo større skærmen er, jo større er afstanden. Da vi blev enig om ikke at crop billeder, kan jeg ikke rigtig se hvad vi skal kunne gøre uden at ødelægge designet.

**Comment by rfenklt** [comment]
Arbejder containeren og billederne ikke uafhængigt af hinanden? Kunne man ikke give containeren en regel om at der atid skal være X-antal pixels fra tekst til bunden af containeren, efterfuldt af knappen 'Kan vi hjælpe dig?'?

**Comment by Mahnkopf** [comment]
fixed
